name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/_build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172854b4087a48e8e8b5a5461e7c # v4.1.7
        with:
          name: dist
          path: dist/

      - uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v4.0.2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::983936649797:role/fem-cicd-service-gha-deploy

      - run: aws s3 sync dist/ s3://arnbrnql-fem-cicd-service/ --delete